/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    MainFooter: typeof import('./src/views/MainFooter.vue')['default']
    MainHeader: typeof import('./src/views/MainHeader.vue')['default']
    MainMiddle: typeof import('./src/views/MainMiddle.vue')['default']
    NavBar: typeof import('./src/views/NavBar.vue')['default']
    UserInfo: typeof import('./src/views/UserInfo.vue')['default']
  }
}
